server:
  port: 80
frontend:
  url:
    - http://localhost:5173/
    - https://valuation-diamond.vercel.app

spring:
  application:
    name: valuationdiamond
  datasource:
    primary:
      jdbc-url: jdbc:sqlserver://database.techtheworld.id.vn:1433;encrypt=true;trustServerCertificate=true;databaseName=diamond_valuation_db
      username: valuationdiamond
      password: 6CB754DB-FE43-478F-BB09-C4B0E5406A2C
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    secondary:
      jdbc-url: jdbc:sqlserver://database.techtheworld.id.vn:1433;encrypt=true;trustServerCertificate=true;databaseName=diamond_valuation_db2
      username: valuationdiamond
      password: 6CB754DB-FE43-478F-BB09-C4B0E5406A2C
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  mail:
    host: smtp.gmail.com
    port: 587
    username: giakhoi060708@gmail.com
    password: pqho vqrn nhco pbiz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        use_sql_comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    date-format = yyyy-MM-dd'T'HH:mm:ss.SSSXXX